name: Build

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    name: Linux-Build
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        # https://www.glfw.org/docs/latest/compile_guide.html#compile_deps_x11
        run: |
          sudo apt-get update
          sudo apt-get install libwayland-dev libxkbcommon-dev xorg-dev ninja-build
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fix Tag Checkout
        run: git fetch --tags --force
      - name: Configure
        run: >-
          cmake -S . -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DSATISFACTORY3DMAP_BUILD_PIC=OFF
      - name: Build
        run: cmake --build ${{github.workspace}}/build
      - name: Print file hash
        run: sha256sum ${{github.workspace}}/build/map/Satisfactory3DMap
      - uses: actions/upload-artifact@v4
        with:
          name: Satisfactory3DMap-Linux
          path: ${{github.workspace}}/build/map/Satisfactory3DMap

  windows:
    name: Windows-Build
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fix Tag Checkout
        run: git fetch --tags --force
      - name: Configure
        run: >-
          cmake -S . -B ${{github.workspace}}/build -G "Visual Studio 17 2022"
          -DSATISFACTORY3DMAP_DISABLE_CONSOLE=ON
          -DSATISFACTORY3DMAP_BUILD_PIC=OFF
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 4
      - name: Print file hash
        run: Get-FileHash ${{github.workspace}}/build/map/${{env.BUILD_TYPE}}/Satisfactory3DMap.exe
      - uses: actions/upload-artifact@v4
        with:
          name: Satisfactory3DMap-Windows
          path: ${{github.workspace}}/build/map/${{env.BUILD_TYPE}}/Satisfactory3DMap.exe

  shader:
    name: Shader-Validation
    runs-on: ubuntu-22.04
    steps:
      - name: Install glslangValidator
        run: |
          sudo apt-get update
          sudo apt-get install glslang-tools
      - uses: actions/checkout@v4
      - name: Run glslang
        run: |
          glslangValidator map/resources/shaders/*

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: [ linux, windows ]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Satisfactory3DMap-Linux
      - name: Zip Linux
        run: zip -9 Satisfactory3DMap-Linux.zip Satisfactory3DMap
      - uses: actions/download-artifact@v4
        with:
          name: Satisfactory3DMap-Windows
      - name: Zip Windows
        run: zip -9 Satisfactory3DMap-Windows.zip Satisfactory3DMap.exe
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Satisfactory3DMap-Linux.zip
            Satisfactory3DMap-Windows.zip
